#	Sabin Raj Tiwari
#	CMSC 621
#	Project 2

compile: part_one part_two directories

part_one:
	g++ -o part_one part_one.cpp

part_two:
	g++ -o part_two part_two.cpp -lpthread -lm

clean:
	rm -f part_one part_two
	rm -rf logs

directories:
	mkdir -p logs